Resources:
#thi is my vpc
  ourVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
     ##private subnet
  subnetPrivate:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-2a
      VpcId: !Ref ourVPC
      CidrBlock: 10.0.0.0/24
      ###public subnet
  subnetPublic:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-2b
      VpcId: !Ref ourVPC
      CidrBlock: 10.0.1.0/24 
      ##public route   
  PublicRouteTable:
        Type: 'AWS::EC2::RouteTable'
        Properties:
          VpcId: !Ref ourVPC
          ###assaciating route table to subnet
  PublicSubnetRouteTableAssociation:
        Type: 'AWS::EC2::SubnetRouteTableAssociation'
        Properties:
          SubnetId: !Ref subnetPublic
          RouteTableId: !Ref PublicRouteTable
          #internet gateway
  igwWorld:
    Type: AWS::EC2::InternetGateway
  routePublic:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref igwWorld

     



