Resources:
#thi is my vpc
  ourVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
     ##private subnet
  subnetPrivate:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-2a
      VpcId: !Ref ourVPC
      CidrBlock: 10.0.0.0/24
      ###public subnet
  subnetPublic:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-2b
      VpcId: !Ref ourVPC
      CidrBlock: 10.0.1.0/24 
      ##public route   
  PublicRouteTable:
        Type: 'AWS::EC2::RouteTable'
        Properties:
          VpcId: !Ref ourVPC
  igw527:
    Type: AWS::EC2::InternetGateway
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: ourVPC
      InternetGatewayId: !Ref igw527               
   



     



